export const CHARACTER_NAMES = {
  // Random name pools by gender with Gen-Z appropriate names
  maleNames: [
    'Liam', 'Noah', 'Oliver', 'Elijah', 'Lucas', 'Mason', 'Logan', 'Ethan', 'Aiden',
    'James', 'Benjamin', 'William', 'Jacob', 'Michael', 'Caleb', 'Daniel', 'Jackson',
    'Sebastian', 'Jack', 'Owen', 'Grayson', 'Julian', 'Levi', 'Mateo', 'Josiah',
    'Henry', 'Theodore', 'Wyatt', 'Gabriel', 'Samuel', 'Carter', 'Jayden', 'John',
    'Dylan', 'Luke', 'Asher', 'Oscar', 'Isaac', 'Parker', 'Nolan', 'Ryan', 'Peter',
    'Miles', 'Ezra', 'Hudson', 'Nathaniel', 'Connor', 'Jeremiah', 'Cameron', 'Santiago',
    'Evan', 'Angel', 'Adrian', 'Xavier', 'Kai', 'Jaxson', 'Easton', 'Everett', 'Glenn',
    'Maverick', 'Silas', 'Carson', 'Luka', 'Rowan', 'Axel', 'Bodhi', 'River',
    'Kai', 'Zen', 'Phoenix', 'Orion', 'Atlas', 'Arlo', 'Sage', 'Wilder', 'Finn',
    'Jasper', 'Cyrus', 'Ronan', 'Zion', 'Apollo', 'Stellan', 'Caspian',
    'Storm', 'Blaze', 'Ace', 'Rex', 'Wolf', 'Fox', 'Hawk', 'Jett', 'Dash', 'Knox',
    'Elio', 'Koa', 'Zayn', 'Kairo', 'Jax', 'Ryker', 'Zander', 'Kieran', 'Jude',
    'Caspian', 'Ocean', 'Forest', 'Jupiter', 'Mars', 'Mercury', 'Sol', 'Cosmo',
    'Nova', 'Sirius', 'Altair', 'Rigel', 'Vega', 'Draco', 'Leo', 'Orion', 'Cygnus',
    'Ash', 'Clay', 'Dune', 'Flint', 'Grove', 'Heath', 'Lake', 'Moss', 'Reef',
    'Stone', 'Tide', 'Wave', 'Bay', 'Brook', 'Creek', 'Dale', 'Glen', 'Ridge',
    'Zephyr', 'Boreas', 'Notus', 'Eurus', 'Aeolus', 'Chinook', 'Sirocco', 'Mistral',
    'Eon', 'Epoch', 'Era', 'Aeon', 'Chronos', 'Kairos', 'Tempus', 'Hora',
    'Cipher', 'Nova', 'Zenon', 'Axon', 'Pixel', 'Vector', 'Matrix', 'Quantum',
    'Neo', 'Echo', 'Cipher', 'Halo', 'Prism', 'Flux', 'Vortex', 'Nexus', 'Vertex',
    'Onyx', 'Jet', 'Coal', 'Slate', 'Flint', 'Obsidian', 'Graphite', 'Charcoal',
    'Zenith', 'Nadir', 'Apex', 'Summit', 'Pinnacle', 'Crest', 'Peak', 'Vertex',
    'Rogue', 'Rebel', 'Maverick', 'Renegade', 'Outlaw', 'Vandal', 'Bandit', 'Ranger',
    'Legend', 'Myth', 'Fable', 'Saga', 'Epic', 'Tale', 'Story', 'Chronicle'
  ],

  // Male-preferring last names (stronger masculine associations)
  maleLastNames: [
    'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis', 'Rodriguez',
    'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore', 'Jackson', 'Martin', 'Lee', 'Vey',
    'Thompson', 'White', 'Harris', 'Clark', 'Ramirez', 'Lewis', 'Robinson', 'Walker',
    'Young', 'Allen', 'King', 'Wright', 'Scott', 'Torres', 'Nguyen', 'Hill', 'Flores',
    'Green', 'Adams', 'Baker', 'Gonzalez', 'Nelson', 'Carter', 'Mitchell', 'Perez',
    'Roberts', 'Turner', 'Phillips', 'Campbell', 'Parker', 'Evans', 'Edwards', 'Collins',
    'Stewart', 'Sanchez', 'Morris', 'Rogers', 'Reed', 'Cook', 'Morgan', 'Bell', 'Murphy',
    'Bailey', 'Cooper', 'Richardson', 'Cox', 'Howard', 'Ward', 'Torres', 'Peterson', 'Gray',
    'Ramirez', 'James', 'Watson', 'Brooks', 'Kelly', 'Sanders', 'Price', 'Bennett', 'Wood',
    'Barnes', 'Ross', 'Henderson', 'Coleman', 'Jenkins', 'Perry', 'Powell', 'Long', 'Patterson',
    'Hughes', 'Flores', 'Washington', 'Butler', 'Simmons', 'Foster', 'Gonzalez', 'Bryant', 'Alexander',
    'Russell', 'Griffin', 'Diaz', 'Hayes', 'Myers', 'Ford', 'Hamilton', 'Graham', 'Sullivan', 'Wallace'
  ],

  femaleNames: [
    'Olivia', 'Emma', 'Ava', 'Sophia', 'Isabella', 'Mia', 'Mira', 'Charlotte', 'Amelia',
    'Harper', 'Evelyn', 'Abigail', 'Emily', 'Elizabeth', 'Sofia', 'Avery', 'Ella', 'Anya',
    'Madison', 'Scarlett', 'Victoria', 'Aria', 'Grace', 'Chloe', 'Camila', 'Penelope',
    'Riley', 'Zoey', 'Nora', 'Hannah', 'Lily', 'Addison', 'Luna', 'Aubrey', 'Ellie', 'Ellen', 'Eleanor',
    'Stella', 'Natalie', 'Zoe', 'Leah', 'Hazel', 'Violet', 'Aurora', 'Savannah',
    'Audrey', 'Brooklyn', 'Bella', 'Claire', 'Skylar', 'Lucy', 'Paisley', 'Everly',
    'Anna', 'Caroline', 'Nova', 'Genesis', 'Emilia', 'Kennedy', 'Samantha', 'Maya',
    'Kinsley', 'Naomi', 'Aaliyah', 'Elena', 'Sarah', 'Ariana', 'Allison', 'Kara',
    'Gabriella', 'Alice', 'Madelyn', 'Cora', 'Ruby', 'Eva', 'Seraphina', 'Lyra', 'Elara',
    'Rose', 'Iris', 'Luna', 'Hazel', 'Ivy', 'Ruby', 'Dawn', 'Skye', 'Wren', 'Clara', 'Carla',
    'Poppy', 'Briar', 'Fern', 'Olive', 'Jade', 'Pearl', 'Celeste', 'Orla', 'Elara',
    'Kehlani', 'Billie', 'Zendaya', 'Remi', 'Nyla', 'Kai', 'Indigo', 'Aurelia', 'Sienna',
    'Calliope', 'Juniper', 'Marlowe', 'Thea', 'Elodie', 'Wrenley', 'Arden', 'Loxley',
    'Sloane', 'Blair', 'Quinn', 'Reese', 'Kensington', 'Presley', 'Rachel', 'Lena',
    'Monroe', 'Harlow', 'Kinslee', 'Ensley', 'Finley', 'Tinsley', 'Brinley', 'Rylie',
    'Oakley', 'Ember', 'Nova', 'Lyra', 'Athena', 'Freya', 'Lilith', 'Persephone',
    'Ophelia', 'Cassia', 'Elara', 'Seraphine', 'Evangeline', 'Genevieve', 'Maxine',
    'Juno', 'Celestia', 'Nebula', 'Solstice', 'Equinox', 'Roche', 'Velvet',
    'Zenith', 'Vesper', 'Liora', 'Zara', 'Amara', 'Idris', 'Clementine', 'Marigold',
    'Primrose', 'Bluebell', 'Snowdrop', 'Lisa', 'Lavender', 'Amanda', 'Yuna',
    'Aria', 'Lyra', 'Nova', 'Celeste', 'Stella', 'Luna', 'Aurora', 'Vega', 'Nova',
    'Serenity', 'Harmony', 'Melody', 'Rhythm', 'Cadence', 'Lyric', 'Sonnet', 'Verse',
    'Willow', 'Ivy', 'Fern', 'Briar', 'Meadow', 'Daisy', 'Clover', 'Sage', 'Hazel',
    'Ocean', 'River', 'Rain', 'Storm', 'Sky', 'Star', 'Moon', 'Sun', 'Cloud',
    'Zephyr', 'Breeze', 'Gale', 'Mist', 'Dew', 'Frost', 'Snow', 'Ice', 'Crystal',
    'Phoenix', 'Raven', 'Wren', 'Sparrow', 'Lark', 'Dove', 'Hawk', 'Falcon', 'Eagle',
    'Onyx', 'Jade', 'Ruby', 'Pearl', 'Amber', 'Garnet', 'Opal', 'Topaz', 'Emerald',
    'Zion', 'Eden', 'Arcadia', 'Shangri-La', 'Utopia', 'Elysium', 'Valhalla', 'Olympus',
    'Electra', 'Andromeda', 'Cassiopeia', 'Callisto', 'Europa', 'Io', 'Ganymede', 'Titan',
    'Xena', 'Artemis', 'Athena', 'Hera', 'Persephone', 'Demeter', 'Hestia', 'Nike',
    'Valkyrie', 'Amazon', 'Siren', 'Nymph', 'Muse', 'Fury', 'Grave', 'Destiny',
    'Echo', 'Nyx', 'Selene', 'Aurora', 'Eos', 'Hemera', 'Thalia', 'Calliope',
    'Kaia', 'Nyla', 'Zara', 'Lyra', 'Veda', 'Sia', 'Kora', 'Mila', 'Nia',
    'Aaliyah', 'Amara', 'Anaya', 'Aziza', 'Bria', 'Cia', 'Dara', 'Elina', 'Fara',
    'Zuri', 'Nia', 'Amara', 'Zola', 'Kendi', 'Makena', 'Nala', 'Zara', 'Yara'
  ],

  femaleLastNames: [
    'Rose', 'Hazel', 'Ivy', 'Ruby', 'Dawn', 'Skye', 'Vance', 'Blackwood',
    'Bloom', 'Winters', 'Summers', 'Bliss', 'Grace', 'Hope', 'Joy', 'Faith', 'Love', 'Star',
    'Angel', 'Dream', 'Moon', 'Sun', 'Cloud', 'Rain', 'Storm', 'Blaze', 'Frost', 'Snow', 'Voss',
    'Meadow', 'Brook', 'River', 'Ocean', 'Wave', 'Breeze', 'Dew', 'Mist', 'Crystal', 'Pearl',
    'Iris', 'Lily', 'Daisy', 'Tulip', 'Violet', 'Poppy', 'Marigold', 'Azalea', 'Camellia', 'Jasmine',
    'Rosewood', 'Moonlight', 'Starlight', 'Sunshine', 'Rainbow', 'Butterfly', 'Phoenix', 'Serenity',
    'Harmony', 'Melody', 'Rhythm', 'Cadence', 'Lyric', 'Sonnet', 'Poem', 'Verse', 'Story', 'Tale',
    'Whisper', 'Echo', 'Silence', 'Calm', 'Peace', 'Zen', 'Bliss', 'Joy', 'Glee', 'Cheer', 'Vera',
    'Sparkle', 'Glitter', 'Shimmer', 'Glimmer', 'Glow', 'Shine', 'Bright', 'Radiant', 'Luminous',
    'Celeste', 'Stella', 'Nova', 'Luna', 'Aurora', 'Orion', 'Vega', 'Lyra', 'Cassiopeia', 'Carinae',
    'Meteora', 'Lynn', 'Nyx', 'Patel', 'Shah', 'Verma', 'Malhotra', 'Agarwal', 'Jain', 'Gabriela',
    'Rosa', 'Maria', 'Sofia', 'Isabella', 'Catalina', 'Valentina', 'Emilia', 'Camila', 'Lucia',
    'Yoon', 'Lim', 'Han', 'Shin', 'Chen', 'Apolonia', 'Cassiopeia', 'Lunaria', 'Stellaria',
    'Garcia', 'Rivera', 'Oliveira', 'Ferreira', 'Costa', 'Almeida', 'Rocha'
  ],

  // Gender-neutral last names (modern and Gen-Z appropriate)
  neutralLastNames: [
    'Stone', 'Wolf', 'Fox', 'Hawk', 'Raven', 'Crow', 'Phoenix', 'Falcon', 'Eagle', 'Hawk',
    'River', 'Brook', 'Stone', 'Rock', 'Cliff', 'Ridge', 'Peak', 'Summit', 'Valley', 'Meadow',
    'Wolf', 'Bear', 'Lion', 'Tiger', 'Eagle', 'Hawk', 'Falcon', 'Raven', 'Crow', 'Phoenix',
    'Storm', 'Blaze', 'Frost', 'Ice', 'Snow', 'Rain', 'Thunder', 'Lightning', 'Shadow', 'Night',
    'Star', 'Moon', 'Sun', 'Sky', 'Cloud', 'Wind', 'Earth', 'Fire', 'Water', 'Spirit',
    'Silver', 'Gold', 'Bronze', 'Copper', 'Steel', 'Iron', 'Crystal', 'Diamond', 'Ruby', 'Jade',
    'Rowan', 'Sage', 'Wren', 'Linden', 'Indigo', 'Marlowe', 'August', 'Sawyer', 'Robin', 'Taylor',
    'Morgan', 'Casey', 'Drew', 'Jamie', 'Jordan', 'Taylor', 'Logan', 'Casey', 'Dakota', 'River',
    'August', 'Sage', 'Wren', 'Linden', 'Indigo', 'Marlowe', 'Rowan', 'Robin', 'Taylor', 'Morgan'
  ]
}