/**
 * Companion SSE Streaming & Incremental JSON Extractor
 *
 * Wraps `aiStreamSSE` from `./ai-chat-stream.js` for the Reader Companion panel.
 * Extracts and yields real-time prose tokens for the `"answer"` field as they are
 * generated by the LLM, without streaming raw JSON brackets or syntax to the client.
 *
 * On stream completion, parses structured metadata (`sources`, `suggestedFollowUps`).
 */

import { aiStreamSSE } from "./ai-chat-stream.js";
import { AI_CHAT_MODELS_WRITING } from "../config/ai-clients.js";
import { AI_CHAT_CONFIG_DEFAULT } from "../config/ai-chat.js";
import { COMPANION_SYSTEM, COMPANION_RESULT_SCHEMA, COMPANION_RESULT_REQUIRED_FIELDS, type CompanionResult } from "./companion-prompt.js";
import type { AIChatStreamProvider } from "../types/sse.js";

/**
 * Completeness validator for a companion answer. Shared by the streaming
 * (`streamCompanionAnswerSSE`) and non-streaming (`aiPrompt`) companion paths so
 * both reject truncated / empty JSON with the identical rule: the parsed payload
 * must contain a non-empty `answer`. Mirrors `aiStreamSSE`'s `validateOutput`
 * contract (`(fullText: string) => boolean`).
 */
export function companionAnswerIsComplete(fullText: string): boolean {
  try {
    const parsed = JSON.parse(fullText.trim());
    return typeof parsed?.answer === "string" && parsed.answer.trim().length > 0;
  } catch {
    return false;
  }
}

/**
 * State machine for incrementally extracting the "answer" string value from a streaming JSON payload.
 * Optimized for O(N) single-pass cursor processing with zero redundant buffer rescans.
 */
export class StreamingJsonAnswerExtractor {
  private buffer = "";
  private answerText = "";
  private inAnswer = false;
  private isDoneAnswer = false;
  private inEscape = false;
  private cursor = 0;

  /**
   * Processes a new delta text chunk from the LLM stream.
   * Returns any newly decoded prose characters that belong to the "answer" field.
   */
  public push(delta: string): string {
    this.buffer += delta;

    // If answer already closed, do nothing further with delta emission
    if (this.isDoneAnswer) {
      return "";
    }

    // Step 1: Find the start of `"answer": "` if not already found
    if (!this.inAnswer) {
      const match = this.buffer.match(/"answer"\s*:\s*"/);
      if (match && match.index !== undefined) {
        this.inAnswer = true;
        this.cursor = match.index + match[0].length;
      } else {
        return "";
      }
    }

    // Step 2: Incrementally process characters from this.cursor onward (O(N) linear time)
    let newlyDecoded = "";
    while (this.cursor < this.buffer.length) {
      const char = this.buffer[this.cursor];

      if (this.inEscape) {
        if (char === "n") newlyDecoded += "\n";
        else if (char === "t") newlyDecoded += "\t";
        else if (char === "r") newlyDecoded += "\r";
        else if (char === '"') newlyDecoded += '"';
        else if (char === "\\") newlyDecoded += "\\";
        else if (char === "/") newlyDecoded += "/";
        else if (char === "u" && this.cursor + 4 < this.buffer.length) {
          const hex = this.buffer.slice(this.cursor + 1, this.cursor + 5);
          try {
            newlyDecoded += String.fromCharCode(parseInt(hex, 16));
            this.cursor += 4;
          } catch {
            newlyDecoded += char;
          }
        } else {
          newlyDecoded += char;
        }
        this.inEscape = false;
      } else if (char === "\\") {
        this.inEscape = true;
      } else if (char === '"') {
        // Unescaped closing quote — end of answer string
        this.isDoneAnswer = true;
        this.cursor++;
        break;
      } else {
        newlyDecoded += char;
      }

      this.cursor++;
    }

    this.answerText += newlyDecoded;
    return newlyDecoded;
  }

  /**
   * Finalizes parsing once the stream has completed.
   * Extracts structured CompanionResult from full JSON or fallback.
   */
  public finalize(): CompanionResult {
    const fullText = this.buffer.trim();

    // 1. Try standard JSON parse
    try {
      const parsed = JSON.parse(fullText);
      if (parsed && typeof parsed.answer === "string") {
        return {
          answer: parsed.answer,
          sources: Array.isArray(parsed.sources) ? parsed.sources.filter((s: unknown): s is string => typeof s === "string") : [],
          suggestedFollowUps: Array.isArray(parsed.suggestedFollowUps)
            ? parsed.suggestedFollowUps.filter((f: unknown): f is string => typeof f === "string")
            : [],
        };
      }
    } catch {
      // JSON may have slight trailing truncation or markdown wrapping
    }

    // 2. Try JSON extraction from code block / regex
    try {
      const jsonMatch = fullText.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0]);
        if (parsed && typeof parsed.answer === "string") {
          return {
            answer: parsed.answer,
            sources: Array.isArray(parsed.sources) ? parsed.sources : [],
            suggestedFollowUps: Array.isArray(parsed.suggestedFollowUps) ? parsed.suggestedFollowUps : [],
          };
        }
      }
    } catch {
      // Continue to regex fallback
    }

    // 3. Fallback: extract via regex or use accumulated answerText
    let extractedSources: string[] = [];
    let extractedFollowUps: string[] = [];

    const sourcesMatch = fullText.match(/"sources"\s*:\s*\[([\s\S]*?)\]/);
    if (sourcesMatch) {
      try {
        extractedSources = JSON.parse(`[${sourcesMatch[1]}]`);
      } catch {
        // ignore
      }
    }

    const followUpsMatch = fullText.match(/"suggestedFollowUps"\s*:\s*\[([\s\S]*?)\]/);
    if (followUpsMatch) {
      try {
        extractedFollowUps = JSON.parse(`[${followUpsMatch[1]}]`);
      } catch {
        // ignore
      }
    }

    const finalAnswer =
      this.answerText.trim() ||
      fullText.replace(/```(?:json)?/g, "").trim() ||
      "I couldn't find an answer based on the current story context.";

    return {
      answer: finalAnswer,
      sources: extractedSources,
      suggestedFollowUps: extractedFollowUps,
    };
  }
}

export interface StreamCompanionAnswerParams {
  userPrompt: string;
  signal?: AbortSignal;
  onChunk: (contentChunk: string) => Promise<void> | void;
  /**
   * Called when the orchestrator falls back to the next provider after a
   * non-terminal failure. The caller should forward this to the client (as an
   * `event: provider_error`) so the UI can clear any partially-streamed text
   * before the next provider begins — otherwise the failed provider's ghost
   * text lingers and then concatenates with the fallback's full output.
   */
  onProviderError?: (message?: string) => void | Promise<void>;
}

export interface StreamCompanionAnswerResult {
  result: CompanionResult;
  aiUsed?: AIChatStreamProvider;
}

/**
 * Executes a true SSE stream for the Companion AI using `aiStreamSSE`.
 * Calls `onChunk` with newly decoded plain-text answer tokens as they arrive,
 * and returns the final parsed `CompanionResult`.
 */
export async function streamCompanionAnswerSSE(
  params: StreamCompanionAnswerParams
): Promise<StreamCompanionAnswerResult> {
  const { userPrompt, signal, onChunk, onProviderError } = params;

  const streamResult = await aiStreamSSE(
    userPrompt,
    {
      modelSelection: AI_CHAT_MODELS_WRITING, // TODO: should use `AI_CHAT_MODELS_FAST` when stable
      context: "companion-ask",
      systemPrompt: COMPANION_SYSTEM,
      outputAsJson: true,
      outputJsonStructure: COMPANION_RESULT_SCHEMA,
      outputJsonRequired: COMPANION_RESULT_REQUIRED_FIELDS,
      config: { ...AI_CHAT_CONFIG_DEFAULT, maxOutputToken: 1024 },
      // Completeness guard: a truncated JSON stream would otherwise be accepted
      // as success and `StreamingJsonAnswerExtractor.finalize()` would happily
      // return a partial `answer`. Reject anything that doesn't parse to a
      // CompanionResult with a non-empty `answer` so aiStreamSSE falls through
      // to the next model/provider instead of serving a cut-off response.
      validateOutput: companionAnswerIsComplete,
    },
    signal
  );

  let extractor = new StreamingJsonAnswerExtractor();
  const decoder = new TextDecoder();
  let currentEventType = '';

  // Iterate over raw SSE stream chunks from aiStreamSSE. aiStreamSSE emits
  // `event: provider_error` frames when it falls back to the next provider, and
  // a terminal `event: error` ("All providers failed") when every attempt is
  // exhausted. We must (a) reset the extractor on a fallback so the next
  // provider's full re-stream isn't concatenated onto the failed one's partial
  // output, and (b) forward `provider_error` to the client (onProviderError) so
  // its UI can clear its own ghost text before the fallback begins.
  for await (const rawChunk of streamResult.stream) {
    if (signal?.aborted) break;

    const chunkText = decoder.decode(rawChunk, { stream: true });
    const lines = chunkText.split("\n");

    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed.startsWith("event: ")) {
        currentEventType = trimmed.slice(7).trim();
        continue;
      }
      if (!line.startsWith("data: ")) continue;

      const payload = line.substring(6);

      // Non-terminal fallback: discard the failed provider's partial text and
      // tell the client to clear its display before the next attempt.
      if (currentEventType === "provider_error") {
        extractor = new StreamingJsonAnswerExtractor();
        let msg: string | undefined;
        try {
          const d = JSON.parse(payload);
          if (typeof d?.message === "string") msg = d.message;
        } catch {
          // Ignore malformed payload — message is optional.
        }
        await onProviderError?.(msg);
        currentEventType = "";
        continue;
      }

      // Terminal failure — surface it to the caller (route emits `event: error`).
      // No extractor reset needed: we throw before finalize() runs, so any
      // partial text buffered so far is discarded.
      if (currentEventType === "error") {
        let msg = "All providers failed";
        try {
          const d = JSON.parse(payload);
          if (typeof d?.message === "string") msg = d.message;
        } catch {
          // Ignore malformed payload.
        }
        throw new Error(msg);
      }

      // Prose frame (event: chunk, or default "message" with no event type).
      try {
        const data = JSON.parse(payload);
        const isProse = currentEventType === "chunk" || currentEventType === "";
        const delta = isProse ? (data.content ?? "") : "";
        if (delta) {
          const emittedText = extractor.push(delta);
          if (emittedText) await onChunk(emittedText);
        }
      } catch {
        // Malformed JSON — treat as raw prose only for prose frames.
        if (currentEventType === "chunk" || currentEventType === "") {
          const emittedText = extractor.push(payload);
          if (emittedText) await onChunk(emittedText);
        }
      }
      currentEventType = "";
    }
  }

  // Await AI provider/model metadata if available
  let aiUsed: AIChatStreamProvider | undefined;
  if (streamResult.provider) {
    try {
      aiUsed = await streamResult.provider;
    } catch {
      // Ignore
    }
  }

  const finalResult = extractor.finalize();
  return { result: finalResult, aiUsed };
}
