/**
 * Companion SSE Streaming & Incremental JSON Extractor
 *
 * Wraps `aiStreamSSE` from `./ai-chat-stream.js` for the Reader Companion panel.
 * Extracts and yields real-time prose tokens for the `"answer"` field as they are
 * generated by the LLM, without streaming raw JSON brackets or syntax to the client.
 *
 * On stream completion, parses structured metadata (`sources`, `suggestedFollowUps`).
 */

import { aiStreamSSE } from "./ai-chat-stream.js";
import { AI_CHAT_MODELS_WRITING } from "../config/ai-clients.js";
import { AI_CHAT_CONFIG_DEFAULT } from "../config/ai-chat.js";
import { COMPANION_SYSTEM, COMPANION_RESULT_SCHEMA, COMPANION_RESULT_REQUIRED_FIELDS, type CompanionResult } from "./companion-prompt.js";
import type { AIChatStreamProvider } from "../types/sse.js";

/**
 * State machine for incrementally extracting the "answer" string value from a streaming JSON payload.
 * Optimized for O(N) single-pass cursor processing with zero redundant buffer rescans.
 */
export class StreamingJsonAnswerExtractor {
  private buffer = "";
  private answerText = "";
  private inAnswer = false;
  private isDoneAnswer = false;
  private inEscape = false;
  private cursor = 0;

  /**
   * Processes a new delta text chunk from the LLM stream.
   * Returns any newly decoded prose characters that belong to the "answer" field.
   */
  public push(delta: string): string {
    this.buffer += delta;

    // If answer already closed, do nothing further with delta emission
    if (this.isDoneAnswer) {
      return "";
    }

    // Step 1: Find the start of `"answer": "` if not already found
    if (!this.inAnswer) {
      const match = this.buffer.match(/"answer"\s*:\s*"/);
      if (match && match.index !== undefined) {
        this.inAnswer = true;
        this.cursor = match.index + match[0].length;
      } else {
        return "";
      }
    }

    // Step 2: Incrementally process characters from this.cursor onward (O(N) linear time)
    let newlyDecoded = "";
    while (this.cursor < this.buffer.length) {
      const char = this.buffer[this.cursor];

      if (this.inEscape) {
        if (char === "n") newlyDecoded += "\n";
        else if (char === "t") newlyDecoded += "\t";
        else if (char === "r") newlyDecoded += "\r";
        else if (char === '"') newlyDecoded += '"';
        else if (char === "\\") newlyDecoded += "\\";
        else if (char === "/") newlyDecoded += "/";
        else if (char === "u" && this.cursor + 4 < this.buffer.length) {
          const hex = this.buffer.slice(this.cursor + 1, this.cursor + 5);
          try {
            newlyDecoded += String.fromCharCode(parseInt(hex, 16));
            this.cursor += 4;
          } catch {
            newlyDecoded += char;
          }
        } else {
          newlyDecoded += char;
        }
        this.inEscape = false;
      } else if (char === "\\") {
        this.inEscape = true;
      } else if (char === '"') {
        // Unescaped closing quote — end of answer string
        this.isDoneAnswer = true;
        this.cursor++;
        break;
      } else {
        newlyDecoded += char;
      }

      this.cursor++;
    }

    this.answerText += newlyDecoded;
    return newlyDecoded;
  }

  /**
   * Finalizes parsing once the stream has completed.
   * Extracts structured CompanionResult from full JSON or fallback.
   */
  public finalize(): CompanionResult {
    const fullText = this.buffer.trim();

    // 1. Try standard JSON parse
    try {
      const parsed = JSON.parse(fullText);
      if (parsed && typeof parsed.answer === "string") {
        return {
          answer: parsed.answer,
          sources: Array.isArray(parsed.sources) ? parsed.sources.filter((s: unknown): s is string => typeof s === "string") : [],
          suggestedFollowUps: Array.isArray(parsed.suggestedFollowUps)
            ? parsed.suggestedFollowUps.filter((f: unknown): f is string => typeof f === "string")
            : [],
        };
      }
    } catch {
      // JSON may have slight trailing truncation or markdown wrapping
    }

    // 2. Try JSON extraction from code block / regex
    try {
      const jsonMatch = fullText.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        const parsed = JSON.parse(jsonMatch[0]);
        if (parsed && typeof parsed.answer === "string") {
          return {
            answer: parsed.answer,
            sources: Array.isArray(parsed.sources) ? parsed.sources : [],
            suggestedFollowUps: Array.isArray(parsed.suggestedFollowUps) ? parsed.suggestedFollowUps : [],
          };
        }
      }
    } catch {
      // Continue to regex fallback
    }

    // 3. Fallback: extract via regex or use accumulated answerText
    let extractedSources: string[] = [];
    let extractedFollowUps: string[] = [];

    const sourcesMatch = fullText.match(/"sources"\s*:\s*\[([\s\S]*?)\]/);
    if (sourcesMatch) {
      try {
        extractedSources = JSON.parse(`[${sourcesMatch[1]}]`);
      } catch {
        // ignore
      }
    }

    const followUpsMatch = fullText.match(/"suggestedFollowUps"\s*:\s*\[([\s\S]*?)\]/);
    if (followUpsMatch) {
      try {
        extractedFollowUps = JSON.parse(`[${followUpsMatch[1]}]`);
      } catch {
        // ignore
      }
    }

    const finalAnswer =
      this.answerText.trim() ||
      fullText.replace(/```(?:json)?/g, "").trim() ||
      "I couldn't find an answer based on the current story context.";

    return {
      answer: finalAnswer,
      sources: extractedSources,
      suggestedFollowUps: extractedFollowUps,
    };
  }
}

export interface StreamCompanionAnswerParams {
  userPrompt: string;
  signal?: AbortSignal;
  onChunk: (contentChunk: string) => Promise<void> | void;
}

export interface StreamCompanionAnswerResult {
  result: CompanionResult;
  aiUsed?: AIChatStreamProvider;
}

/**
 * Executes a true SSE stream for the Companion AI using `aiStreamSSE`.
 * Calls `onChunk` with newly decoded plain-text answer tokens as they arrive,
 * and returns the final parsed `CompanionResult`.
 */
export async function streamCompanionAnswerSSE(
  params: StreamCompanionAnswerParams
): Promise<StreamCompanionAnswerResult> {
  const { userPrompt, signal, onChunk } = params;

  const streamResult = await aiStreamSSE(
    userPrompt,
    {
      modelSelection: AI_CHAT_MODELS_WRITING, // TODO: should use `AI_CHAT_MODELS_FAST` when stable
      context: "companion-ask",
      systemPrompt: COMPANION_SYSTEM,
      outputAsJson: true,
      outputJsonStructure: COMPANION_RESULT_SCHEMA,
      outputJsonRequired: COMPANION_RESULT_REQUIRED_FIELDS,
      config: { ...AI_CHAT_CONFIG_DEFAULT, maxOutputToken: 1024 },
    },
    signal
  );

  const extractor = new StreamingJsonAnswerExtractor();
  const decoder = new TextDecoder();

  // Iterate over raw SSE stream chunks from aiStreamSSE
  for await (const rawChunk of streamResult.stream) {
    if (signal?.aborted) break;

    const chunkText = decoder.decode(rawChunk, { stream: true });
    const lines = chunkText.split("\n");

    for (const line of lines) {
      if (line.startsWith("data: ")) {
        try {
          const data = JSON.parse(line.substring(6));
          // Extract text from data.content (emitted by createTextChunkEvent)
          const delta = data.type === "chunk" ? data.content : data.content || "";
          if (delta) {
            const emittedText = extractor.push(delta);
            if (emittedText) {
              await onChunk(emittedText);
            }
          }
        } catch {
          // If not standard JSON SSE chunk, push raw text
          if (line.substring(6).trim()) {
            const emittedText = extractor.push(line.substring(6));
            if (emittedText) {
              await onChunk(emittedText);
            }
          }
        }
      }
    }
  }

  // Await AI provider/model metadata if available
  let aiUsed: AIChatStreamProvider | undefined;
  if (streamResult.provider) {
    try {
      aiUsed = await streamResult.provider;
    } catch {
      // Ignore
    }
  }

  const finalResult = extractor.finalize();
  return { result: finalResult, aiUsed };
}
