/**
 * Email Utilities
 *
 * Provides transactional email sending via Resend. All public functions delegate
 * to the private `sendEmail` helper, which centralises error handling, logging,
 * and the Resend API call — keeping individual email functions DRY.
 *
 * @example
 * ```typescript
 * import { sendPasswordResetEmail, sendVerificationEmail } from '../utils/email.js';
 *
 * // Send password reset email
 * await sendPasswordResetEmail('user@example.com', 'https://app.com/reset-password?token=xxx');
 *
 * // Send email verification
 * await sendVerificationEmail('user@example.com', 'https://app.com/verify-email?token=xxx');
 * ```
 */

import { Resend } from 'resend';
import { APP_NAME } from '../config/constants.js';
import {
  getPasswordResetTemplate,
  getVerificationTemplate,
  getWelcomeTemplate,
  getTrialEndingTemplate,
  getFeedbackAcknowledgmentTemplate,
} from '../config/emails/index.js';

// ---------------------------------------------------------------------------
// Client initialisation
// ---------------------------------------------------------------------------

/**
 * Resend client singleton.
 *
 * Deferred until the first email is actually sent so that importing this module
 * (or booting the server) never fails when `RESEND_API_KEY` is absent — the
 * client is only constructed inside a request path that needs it.
 */
let resendClient: Resend | null = null;

/**
 * Returns the shared Resend client, creating it on first call.
 *
 * Throws if `RESEND_API_KEY` is not configured; callers already treat email
 * sending as best-effort, so the throw surfaces a clear misconfiguration
 * exactly when an email is attempted rather than at startup.
 *
 * @returns The initialised {@link Resend} client
 */
function getResendClient(): Resend {
  if (resendClient) return resendClient;

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    throw new Error("RESEND_API_KEY is not configured; unable to send email");
  }

  resendClient = new Resend(apiKey);
  return resendClient;
}

/** Default sender address; override via RESEND_FROM_EMAIL env var */
const DEFAULT_FROM_EMAIL = process.env.RESEND_FROM_EMAIL || 'noreply@twistloom.com';

// ---------------------------------------------------------------------------
// Shared send helper
// ---------------------------------------------------------------------------

/**
 * Options passed to the shared send helper.
 */
interface SendEmailOptions {
  /** Recipient email address */
  to: string;
  /** Email subject line */
  subject: string;
  /** Pre-rendered HTML body (generated by a template function) */
  html: string;
  /** Override sender address (defaults to DEFAULT_FROM_EMAIL) */
  from?: string;
}

/**
 * Core send helper — all public email functions eventually call this.
 *
 * Centralises the Resend API call, error handling, and logging so that
 * individual email functions only need to provide subject, recipient, and
 * rendered HTML.
 *
 * @param options - Email sending options
 * @returns `true` if Resend accepted the send, `false` on error
 *
 * Internal note: never throws. Callers that need to distinguish transient
 * failures from permanent ones should inspect the return value.
 */
async function sendEmail(options: SendEmailOptions): Promise<boolean> {
  const { to, subject, html, from } = options;

  try {
    const { error } = await getResendClient().emails.send({
      from: from ?? DEFAULT_FROM_EMAIL,
      to,
      subject,
      html,
    });

    if (error) {
      console.error(`[sendEmail] ❌ Resend API error for "${subject}" to ${to}:`, error);
      return false;
    }

    console.log(`[sendEmail] ✅ "${subject}" sent to ${to}`);
    return true;
  } catch (error) {
    console.error(`[sendEmail] ❌ Failed to send "${subject}" to ${to}:`, error);
    return false;
  }
}

// ---------------------------------------------------------------------------
// Public email functions
// ---------------------------------------------------------------------------

/**
 * Sends a password-reset email containing a one-time reset link.
 *
 * The link expires after 1 hour (enforced server-side by the reset token).
 *
 * @param email - Recipient's email address
 * @param resetUrl - Full password reset URL including the signed token
 * @returns `true` if the email was accepted by Resend, `false` otherwise
 *
 * @example
 * ```typescript
 * const sent = await sendPasswordResetEmail('user@example.com', 'https://app.com/reset-password?token=abc123');
 * if (!sent) {
 *   // Fall back to showing the reset URL directly, or retry
 * }
 * ```
 */
export async function sendPasswordResetEmail(email: string, resetUrl: string): Promise<boolean> {
  return sendEmail({
    to: email,
    subject: `Reset Your ${APP_NAME} Password`,
    html: getPasswordResetTemplate(APP_NAME, resetUrl),
  });
}

/**
 * Sends an email-verification email containing a one-time verification link.
 *
 * The link expires after 24 hours (enforced server-side by the verification token).
 *
 * @param email - Recipient's email address
 * @param verificationUrl - Full verification URL including the signed token
 * @returns `true` if the email was accepted by Resend, `false` otherwise
 *
 * @example
 * ```typescript
 * const sent = await sendVerificationEmail('user@example.com', 'https://app.com/verify-email?token=abc123');
 * ```
 */
export async function sendVerificationEmail(email: string, verificationUrl: string, otpCode?: string): Promise<boolean> {
  return sendEmail({
    to: email,
    subject: `Verify Your ${APP_NAME} Email`,
    html: getVerificationTemplate(APP_NAME, verificationUrl, otpCode),
  });
}

/**
 * Sends a welcome email after successful user signup.
 *
 * Includes a personal greeting from the creator and orients the user to the
 * Twistloom narrative engine.
 *
 * @param email - Recipient's email address
 * @param username - User's chosen display name (for personalisation)
 * @returns `true` if the email was accepted by Resend, `false` otherwise
 *
 * @example
 * ```typescript
 * const sent = await sendWelcomeEmail('user@example.com', 'johndoe');
 * ```
 */
export async function sendWelcomeEmail(email: string, username: string): Promise<boolean> {
  return sendEmail({
    to: email,
    subject: `Welcome to ${APP_NAME}!`,
    html: getWelcomeTemplate(APP_NAME, username),
  });
}

/**
 * Sends a reminder email ~3 days before a user's VIP free trial ends.
 *
 * This is deliberately kept short and plain — the companion in-app notification
 * carries the CTA, and Stripe's own trial-ending email (sent automatically from
 * the Dashboard) serves as a zero-code safety net. The goal is a legible nudge,
 * not a marketing blast.
 *
 * Non-blocking by design: the caller (`handleTrialWillEnd`) wraps this in a
 * try/catch so a Resend failure never breaks the in-app notification or fails
 * the Stripe webhook. Errors are logged here, not thrown.
 *
 * @param email - Recipient's email address
 * @param name - User's display name for personalisation
 * @param trialEndDate - When the trial ends (displayed to the user)
 * @returns `true` if the email was accepted by Resend, `false` otherwise
 *
 * @example
 * ```typescript
 * await sendTrialEndingEmail('user@example.com', 'Jane', new Date('2026-07-15'));
 * ```
 */
export async function sendTrialEndingEmail(email: string, name: string, trialEndDate: Date): Promise<boolean> {
  return sendEmail({
    to: email,
    subject: `Your ${APP_NAME} VIP Trial Ends Soon`,
    html: getTrialEndingTemplate(APP_NAME, name, trialEndDate),
  });
}

/**
 * Sends a thank-you email after a user submits feedback.
 *
 * Confirms receipt, apologizes for any inconvenience, and reassures that the
 * team will address the issue ASAP. Non-blocking by design: callers should
 * wrap this in try/catch so a Resend failure never fails the feedback API.
 *
 * @param email - Recipient's email address
 * @param name - User's display name for personalisation
 * @returns `true` if the email was accepted by Resend, `false` otherwise
 *
 * @example
 * ```typescript
 * await sendFeedbackAcknowledgmentEmail('user@example.com', 'Jane');
 * ```
 */
export async function sendFeedbackAcknowledgmentEmail(email: string, name: string): Promise<boolean> {
  return sendEmail({
    to: email,
    subject: `We Received Your Feedback — ${APP_NAME}`,
    html: getFeedbackAcknowledgmentTemplate(APP_NAME, name),
  });
}
